//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class documente
{
    public int Id { get; set; }
    public Nullable<int> id_eveniment { get; set; }
    public string document { get; set; }
    public string data_incarcare { get; set; }
}

public partial class evenimente
{
    public evenimente()
    {
        this.organizeazas = new HashSet<organizeaza>();
    }

    public int id { get; set; }
    public string nume { get; set; }
    public string descriere { get; set; }
    public string etichete { get; set; }
    public Nullable<System.DateTime> data_inceperii { get; set; }
    public string oras { get; set; }
    public string judet { get; set; }
    public string tara { get; set; }
    public string expunere { get; set; }
    public int id_proprietar { get; set; }

    public virtual ICollection<organizeaza> organizeazas { get; set; }
    public virtual utilizator utilizator { get; set; }
}

public partial class locatie
{
    public int Id { get; set; }
    public string latitudine { get; set; }
    public string longitutine { get; set; }
    public Nullable<int> numar_voturi { get; set; }
}

public partial class organizeaza
{
    public int id_organizator { get; set; }
    public int id_eveniment { get; set; }
    public bool aprobat { get; set; }

    public virtual evenimente evenimente { get; set; }
    public virtual utilizator utilizator { get; set; }
}

public partial class participa
{
    public int id_utilizator { get; set; }
    public int id_rol { get; set; }
    public Nullable<int> id_eveniment { get; set; }
}

public partial class replici
{
    public int Id { get; set; }
    public int id_eveniment { get; set; }
    public int id_parinte { get; set; }
    public string text { get; set; }
    public string autor { get; set; }
    public System.DateTime data { get; set; }
}

public partial class roluri
{
    public int Id { get; set; }
    public Nullable<int> id_eveniment { get; set; }
    public string denumire { get; set; }
    public string descriere { get; set; }
    public Nullable<int> max_participanti { get; set; }
}

public partial class tranzitii
{
    public int Id { get; set; }
    public int id_actiune_initiala { get; set; }
    public Nullable<int> id_actiune_noua { get; set; }
    public string id_rol { get; set; }
    public string min_actori { get; set; }
    public string max_actor { get; set; }
    public string id_locatie { get; set; }
    public Nullable<System.DateTime> data { get; set; }
}

public partial class utilizator
{
    public utilizator()
    {
        this.evenimentes = new HashSet<evenimente>();
        this.organizeazas = new HashSet<organizeaza>();
    }

    public string acont { get; set; }
    public string nume { get; set; }
    public string prenume { get; set; }
    public string email { get; set; }
    public string parola { get; set; }
    public int id { get; set; }
    public string oras { get; set; }
    public string tara { get; set; }
    public string judet { get; set; }

    public virtual ICollection<evenimente> evenimentes { get; set; }
    public virtual ICollection<organizeaza> organizeazas { get; set; }
}
